import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/assets/styles/reset.css";
import "@/assets/styles/globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/features/theme";
import style from './page.module.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}


//https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config
// export const runtime = 'nodejs'
// export const dynamic = 'force-static'
// export const revalidate = 5
// export const fetchCache = 'force-cache'


//NextJS Polyfills
//https://nextjs.org/docs/architecture/supported-browsers#server-side-polyfills

//https://www.youtube.com/watch?v=gSSsZReIFRk (app router guide)
//https://www.youtube.com/watch?v=VBlSe8tvg4U (cacheing in more detail)
//https://www.youtube.com/watch?v=RBM03RihZVs (antipatterns)